n = int(input())
r1= set(int(i) for i in input().split())
m= int(input())
r2= set(int(i) for i in input().split())
#x=r1.union(r2)
#x=r1.intersection(r2)
#x= r1.difference(r2)
x=r1.symmetric_difference(r2)
print(len(x))